name: 'Dhall Validator'
description: 'Validate Dhall files'
author: 'jsoref'
branding:
  icon: 'edit-3'
  color: 'blue'
inputs:
  dhall-binary:
    description: 'Binary of dhall-haskell to use'
    default: 'https://github.com/dhall-lang/dhall-haskell/releases/download/$DHALL_HASKELL/dhall-json-$DHALL_JSON-x86_64-linux.tar.bz2'
    required: false
  dhall-haskell:
    description: 'Version of dhall-haskell'
    default: '1.39.0'
    required: false
  dhall-json:
    description: 'Version of dhall-to-json'
    default: '1.7.7'
    required: false
  dhall-files:
    description: 'List of dhall files to check'
    required: false
  dhall-file-list:
    description: 'Null delimited file of dhall files to check'
    required: false
  verbose:
    description: 'Enable verbose logging'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - id: spelling
      env:
        DHALL_HASKELL: ${{ inputs.dhall-haskell }}
        DHALL_JSON: ${{ inputs.dhall-json }}
        DHALL_BINARY: ${{ inputs.dhall-binary }}
        FILES: ${{ inputs.dhall-files }}
        LIST: ${{ inputs.dhall-file-list }}
        VERBOSE: ${{ inputs.verbose }}
      run:
        $GITHUB_ACTION_PATH/check.sh
      shell: bash
